config/routes.rb
YesDontpanicComUa::Application.routes.draw do
  ActiveAdmin.routes(self)
  mount ImperaviRails::Engine => "/imperavi"

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "pages/index"
  get "pages/about"
  get "pages/blog"
  get "pages/blog_inside"
  get "pages/contact_us"
  get "pages/inside_project"
  get "pages/people"
  get "pages/profile"
  post "pages/send_email"
  post "pages/semd_email", :to => "pages#send_email", :as => "send_email"

  match 'index' => 'pages#index'
  match 'about' => 'pages#about'
  match 'blog' => 'pages#blog'
  match 'blog_inside/:id' => 'pages#blog_inside'
  match 'contact_us' => 'pages#contact_us'
  match 'inside_project/:id' => 'pages#inside_project'
  match 'people' => 'pages#people'
  match 'profile/:id' => 'pages#profile'
  

  resources :images, :only => [:index, :create]

  root :to => 'pages#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  after_create { |admin| admin.send_reset_password_instructions }
  def password_required?
        new_record? ? false : super
  end
  def confirmation_required?
    !confirmed?
  end
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  validates_presence_of :title, :cut, :content
  def self.prev(id)
    return BlogPost.where('blog_posts.id < ?', id).last
  end

  def self.next(id)
    return BlogPost.where('blog_posts.id > ?', id).first
  end
  default_scope order 'created_at desc'
end

app/models/content.rb
class Content < ActiveRecord::Base
  validates_presence_of :identifier
  def self.get_content(identifier)
    return Content.where('contents.identifier = ?', identifier).first.content.html_safe
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  ALLOWED_MIME_TYPES = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']
  ALLOWED_EXTENSIONS = [:jpeg, :jpg, :png, :JPEG, :JPG, :PNG]

  image_accessor :image # accessor to image_uid

  validates :image, :presence => true, :on => :create
  validates :image, :length => { :maximum => 6.megabytes }

  # Dragonfly custom validators for image
  # see: github.com/markevans/dragonfly
  validates_property :format,    :of => :image, :in => ALLOWED_EXTENSIONS
  validates_property :mime_type, :of => :image, :in => ALLOWED_MIME_TYPES
  validates_property :width,     :of => :image, :in => (50..3000)
  validates_property :height,    :of => :image, :in => (50..3000)

  default_scope order 'updated_at desc'
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_attached_file :avatar, 
    :styles => { :small => "150x150>" },
    :url  => "/assets/people/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/people/:id/:style/:basename.:extension"

  validates_presence_of :name, :about
  validates_attachment_presence :avatar
  validates_format_of :twitter_url, :facebook_url, :with => /^((http|https?):\/\/((?:[-a-z0-9]+\.)+[a-z]{2,}))/,
    :message => 'Invalid URL.',
    :allow_blank => true

  has_many :projects
  default_scope order 'created_at desc'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :thumbnail,
    :styles => { :small => "150x150>" },
    :url  => "/assets/projects/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/projects/:id/:style/:basename.:extension"

  validates_presence_of :title,:person, :content
  validates_attachment_presence :thumbnail
  
  def self.works(person_id, project_id)
    return Project.where('projects.person_id = ? and projects.id != ?', person_id, project_id).limit(5)
  end

  belongs_to :person
  default_scope order 'created_at desc'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :create_body_id
  def create_body_id
      @body_id = "#{params[:action]}"
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < InheritedResources::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  skip_before_filter :verify_authenticity_token
  respond_to :html, :json

  def index
    @images = Image.scoped

    respond_with @images do |format|
      format.json { render :json => json_images(@images), :layout => false }
    end
  end

  def create
    @image = Image.new(params[:image])

    if @image.save
      render :text => view_context.image_tag(@image.image.url, :alt => '')
    else
      render :json => @image.errors
    end
  end

  private

  def json_images(images)
    json_images = []

    images.each do |image|
      json_images << {
        :thumb => resize_image(image, 120, 100).url,
        :image => image.image.url
      }
    end

    json_images
  end

  def resize_image(image, width = 100, height = 100, gravity = :c)
    image.image.process(:resize_and_crop, :width => width, :height => height, :gravity => gravity.to_s)
  end
end

app/controllers/pages_controller.rb
#encoding: utf-8
class PagesController < ApplicationController
  def index
    @index_header = Content.get_content('index_header')
    @last = [Project.order("created_at").limit(100).all + BlogPost.order("created_at").limit(100).all]
  end
  def about
    @about_header = Content.get_content('about_header')
    @about_content = Content.get_content('about_content')
  end
  def blog
    @blogs = BlogPost.all
    @blog_header = Content.get_content('blog_header')
  end
  def blog_inside
    id = params[:id].to_i
    @blog = BlogPost.find(id)
    @blogPrev = BlogPost.prev(id)
    @blogNext = BlogPost.next(id)
    @projects = Project.all.shuffle[0..4]
  end
  def contact_us
    @contact_content = Content.get_content('contact_content')
  end
  def inside_project
    @project = Project.find(params[:id])
    @person = Person.find(@project.person_id)
    @works = Project.works(@project.person_id, @project.id)
  end
  def people
    @people = Person.all
    @projects = Project.all.shuffle[0..10]
    @people_header = Content.get_content('people_header')
  end
  def profile
    @person = Person.find(params[:id])
    @works = Project.works(@person.id, 0).shuffle[0..4]
    @people = Person.all.shuffle[0..6]
  end
  def send_email
    require "mail"
    first_name = params[:first_name]
    last_name = params[:last_name]
    message = params[:body]
    mail = Mail.new do
      from     'yes_contact@mail.com'
      to       'whoisjoy@gmail.com'
      subject  'Сообщение от ' + first_name + '  ' + last_name
      body     message
    end
    mail.delivery_method :sendmail
    mail.deliver
    flash[:notice] = "Сообщение отправлено. Спасибо!"
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/people/_projects_list.html.erb
<ul>
  <% projects.each do |p| %>
    <li> <%= link_to p.title, admin_project_path(p) + '/edit'%></li>
  <% end%>
</ul>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="box-link">
    <a href="http://dontpanic.com.ua" class="mini-logo">Don't Panic Kharkov. Making great web-apps.</a>
    <p>Cделано без паники </p>
    <p>&copy; <a href="http://dontpanic.com.ua">DontPanic</a> 2012</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
  <a href="<%= about_path %>" class="link_about">О проекте</a>
  <strong class="logo"><a href="/">Project</a></strong>
    <ul id="navigation">
      <li><a href="<%= people_path%>">Люди</a></li>
      <li><a href="<%= blog_path %>">Блог</a></li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Project</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body id="<%= @body_id %>">
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <div class="wrapper">
      <%= render :partial => 'layouts/header' %>
      <div id='content'>
        <%= yield %>
      </div>
      <%= render :partial => 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="top-panel">
  <div class="text">
    <%= @about_header %>
  </div>
  <div class="likeit">
    <div class="facebook">
      <div class="fb-like" data-send="false" data-width="250" data-show-faces="false"></div>
    </div>
    <div class="twitter">
      <a href="https://twitter.com/share" class="twitter-share-button" data-text="This page is so cool:" data-hashtags="betterthanworse">Tweet</a>
    </div>
  </div>
</div>
<div class="content">
  <h1 class="title-project">О проекте</h1>
  <div class="info">
    <p><%= @about_content %></p>
  </div>
</div>

app/views/pages/blog.html.erb
<div class="top-panel">
  <h1 class="title-blog">Блог</h1>
  <div class="text">
    <p><%= @blog_header %></p>
    <div class="likeit">
      <div class="facebook">
        <div class="fb-like" data-send="false" data-width="250" data-show-faces="false"></div>
      </div>
      <div class="twitter">
        <a href="https://twitter.com/share" class="twitter-share-button" data-text="This page is so cool:" data-hashtags="betterthanworse">Tweet</a>
      </div>
    </div>
  </div>
</div>
<div class="content">
  <% @blogs.each do |blog| %>
  <div class="blog">
    <h2><%= blog.title %></h2>
    <p><%=raw blog.cut %></p>
    <%= link_to 'Читать дальше', 'blog_inside/' + blog.id.to_s, :class=>"more" %>
  </div>
  <% end %>
</div>

app/views/pages/blog_inside.html.erb
<h1><%= @blog.title %></h1>
<div class="main">
  <div class="content">
    <p><%=raw @blog.cut %></p>
    <p><%=raw @blog.content %></p>
    <!--div class="visual">
      <img src="/assets/image02.gif" width="686" height="459" alt="image description" />
    </div-->
    <div class="bottom-panel">
      <% if @blogNext %>
        <%= link_to @blogNext.title + '->', '/blog_inside/' + @blogNext.id.to_s, :class=>"next" %>
      <% end %>
      <% if @blogPrev %>
        <%= link_to '<-' + @blogPrev.title, '/blog_inside/' + @blogPrev.id.to_s, :class=>"prev" %>
      <% end %>
      <div class="likeit">
        <div class="facebook">
          <div class="fb-like" data-send="false" data-show-faces="false"></div>
        </div>
        <div class="twitter">
          <a href="https://twitter.com/share" class="twitter-share-button" data-text="This page is so cool:" data-hashtags="betterthanworse">Tweet</a>
        </div>
      </div>
    </div>
  </div>
  <div class="aside">
    <h2>Еще, похожие на дизайн:</h2>
    <ul class="items-list">
      <% @projects.each do |project| %>
      <li>
      <a href="/inside_project/<%= project.id %>/">
        <%= image_tag(project.thumbnail, :size => "98x97") %>
        <span class="mask"></span>
      </a>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pages/contact_us.html.erb
<div class="top-panel">
  <h1 class="title-connect">Коннект</h1>
  <div class="text">
    <ul class="socials">
      <li>
      <a href="#" class="facebook">facebook</a>
      </li>
      <li>
      <a href="#" class="twitter">twitter</a>
      </li>
    </ul>
    <p>+38/050 920 84 36 <a href="mailto:&#120;&#105;&#110;&#102;&#111;&#064;&#120;&#100;&#099;&#046;&#099;&#111;&#109;&#046;&#117;&#097;">&#120;&#105;&#110;&#102;&#111;&#064;&#120;&#100;&#099;&#046;&#099;&#111;&#109;&#046;&#117;&#097;</a></p>
  </div>
</div>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<div class="content">
    <%= form_tag send_email_path, :class => 'contact-form' do %>
      <fieldset>
        <h2>Раскажите о себе:</h2>
        <div class="row">
          <%= label_tag :first_name, 'Имя:'  %>
          <%= text_field_tag :first_name, nil, :required => true %>
        </div>
        <div class="row">
          <%= label_tag :last_name, 'Фамилия:' %>
          <%= text_field_tag :last_name, nil, :required => true %>
        </div>
        <h2>Немного слов:</h2>
        <%= text_area_tag :body, nil, :rows => 10, :cols =>10, :class => 'area', :required => true %>
        <%= submit_tag "Отправить", :class => 'submit' %>
      </fieldset>
    <% end %>
    <div class="text-box">
    <p><%= @contact_content %></p>
  </div>
</div>

app/views/pages/index.html.erb
<div class="top-panel">
  <div class="text">
    <p>
      <%= @index_header %>
    </p>
    <div class="likeit">
      <div class="facebook">
        <div class="fb-like" data-send="false" data-show-faces="false"></div>
      </div>
      <div class="twitter">
        <a href="https://twitter.com/share" class="twitter-share-button" data-text="This page is so cool:" data-hashtags="betterthanworse">Tweet</a>
      </div>
    </div>
  </div>
</div>
<div class="content">
  <h1 class="title-move">Двигаем Х</h1>
  <div class="slider-wrapper">
    <ul class="slider">
      <% @last[0].sort_by(&:created_at).each do |item| %>
      <li>
        <div class="box">
          <a href="<%= (item.has_attribute?(:cut) ? "blog_inside/" : "inside_project/") + item.id.to_s %>">
            <span class="image">
              <% if (item.has_attribute?(:thumbnail_file_name)) %>
                <%= image_tag(item.thumbnail, :size => "127x127") %>
                <span class="mask"></span>
              <% else %>
                <img src="/assets/img04.gif" alt="description" width="127" height="127" />
                <span class="mask"></span>
              <% end %>
            </span>
            <strong class="title">Из "<%= item.title %>"</strong>
            <% if (item.has_attribute?(:cut)) %>
              <%= strip_tags(item.cut).truncate(200, :separator => '  ') %>
            <% else %>
              <%= strip_tags(item.content).truncate(200, :separator => '  ') %>
            <% end %>
          </a>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
  <% if @last[0].size > 3 %>
    <a class="btn-next">next</a>
  <% end %>
</div>
<script type="text/javascript">
  jQuery(".slider-wrapper").jCarouselLite({
    btnNext: ".btn-next",
    btnPrev: ".btn-prev",
    circular: true,
    scroll: 3,
    speed: 1500
  });
</script>

app/views/pages/inside_project.html.erb
<div class="main">
  <div class="content">
    <h1><%= @project.title %></h1>
    <p><%=raw @project.content %></p>
    <div class="likeit">
       <div class="facebook">
        <div class="fb-like" data-send="false" data-show-faces="false"></div>
      </div>
      <div class="twitter">
        <a href="https://twitter.com/share" class="twitter-share-button" data-text="This page is so cool:" data-hashtags="betterthanworse">Tweet</a>
      </div>
    </div>
  </div>
  <div class="aside">
    <div class="author">
      <div class="photo">
        <%= image_tag(@person.avatar, :size => "71x71") %>
        <span class="mask"></span>
      </div>
      <h3>
        <%= link_to @person.name, '/profile/' + @person.id.to_s %>
    </div>
    <div class="info">
      <% if @works.count > 0 %>
        <h4>Другие работы автора:</h4>
        <ul class="items-list">
        <% @works.each do |work| %>
          <li>
            <a href="/inside_project/<%= work.id %>/">
              <%= image_tag(work.thumbnail, :size => "100x100") %>
              <span class="mask"></span>
            </a>
          </li>
        <% end %>
      </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/people.html.erb
<div class="top-panel">
  <div class="text">
    <%= @people_header %>
  </div>
</div>
<div class="main">
  <div class="title">
    <h1 class="title-people">Люди</h1>
    <div class="likeit">
      <div class="facebook">
        <div class="fb-like" data-send="false" data-width="250" data-show-faces="false"></div>
      </div>
      <div class="twitter">
        <a href="https://twitter.com/share" class="twitter-share-button" data-text="This page is so cool:" data-hashtags="betterthanworse">Tweet</a>
      </div>
    </div>
  </div>
  <div class="content">
    <ul class="photos-list">
      <% @people.each do |person| %>
        <li>
        <a href="/profile/<%= person.id.to_s %>">
          <%= image_tag(person.avatar, :size => "151x151") %>
          <span class="mask"></span>
          </a>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="bottom-box">
    <h2>Случайные работы:</h2>
    <ul class="items-list">
      <% @projects.each do |prj| %>
      <li>
        <a href="/inside_project/<%= prj.id %>/">
          <%= image_tag(prj.thumbnail, :size => "101x101") %>
          <span class="mask"></span>
        </a>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="top-panel">
  <div class="profile">
    <div class="photo-holder">
      <div class="photo">
        <%= image_tag(@person.avatar, :size => "151x151") %>
        <span class="mask"></span>
      </div>
      <ul class="socials">
        <% if !@person.facebook_url.empty? %>
          <li>
            <a href="<%= @person.facebook_url %>"><img src="/assets/facebook.gif" width="19" height="19" alt="facebook" /></a>
          </li>
        <% end %>
        <% if !@person.twitter_url.empty? %>
          <li>
            <a href="<%= @person.twitter_url %>"><img src="/assets/twitter2.gif" width="19" height="19" alt="twitter" /></a>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="text">
      <h1><%= @person.name %></h1>
      <%=raw  @person.about %>
      <div class="likeit">
        <div class="facebook">
          <div class="fb-like" data-send="false" data-width="400" data-show-faces="false"></div>
        </div>
        <div class="twitter">
          <a href="https://twitter.com/share" class="twitter-share-button" data-text="This page is so cool:" data-hashtags="betterthanworse">Tweet</a>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="main">
  <div class="content">
    <% if @works.count > 0 %>
      <p>Я предлагаю:</p>
      <ul class="works-list">
        <% @works.each do |work| %>
          <li>
            <a href="/inside_project/<%= work.id %>/">
              <%= image_tag(work.thumbnail, :size => "174x173") %>
              <span class="mask"></span>
            </a>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="bottom-box">
    <h2>Другие участники:</h2>
    <ul class="items-list">
      <% @people.each do |person| %>
      <li>
      <a href="/profile/<%= person.id.to_s %>">
        <%= image_tag(person.avatar, :size => "101x101") %>
        <span class="mask"></span>
      </a>
      </li>
    <% end %>
    </ul>
  </div>
</div>